const games = [
    {
        id: 'empire',
        name: 'Empire',
        tagline: 'Guess who said what',
        emoji: '👑',
        color: '#2d0808',
        category: 'Social',
        playerCount: '2–20+',
        duration: '10–30 min',
        description: 'Players secretly submit a word, then try to figure out which word belongs to each person. Bluff, deduce, and conquer!',
        rules: [
            'The host sets up the game on a shared screen (TV, laptop, etc.)',
            'Each player joins on their phone and submits a secret word',
            'Optionally, the host can set a category (e.g. "Movies", "Athletes")',
            'Once everyone has submitted, the host starts the game',
            'All words are revealed (shuffled) — but not who wrote them',
            'Players take turns guessing which word belongs to which person',
            'If you guess correctly, that player joins your "empire"',
            'Last player standing wins!'
        ],
        hostPath: '/empire/host',
        playPath: '/empire/play',
    },
    {
        id: 'trivia',
        name: 'Trivia',
        tagline: 'Fast-paced multiple-choice party quiz',
        emoji: '🧠',
        color: '#46178F',
        category: 'Social',
        playerCount: '1–50+',
        duration: '5–15 min',
        description: 'Players join on their phones and race to answer multiple-choice trivia questions. Faster correct answers earn more points. Questions come live from the Open Trivia Database.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'Host picks category, difficulty, number of questions, and time per question',
            'Each question shows 4 colored answer tiles labeled A, B, C, D',
            'Tap the tile you think is correct — faster answers earn more points',
            'After each question, see the bar chart and Top 5 leaderboard',
            'After the final question, the podium reveals the top 3'
        ],
        hostPath: '/trivia/host',
        playPath: '/trivia/play',
    },
    {
        id: 'twentyfour',
        name: '24',
        tagline: 'Race to 24 with four numbers and four operations',
        emoji: '🔢',
        // Render a styled text badge (the orange "24" mark used on the game's
        // own pages) on the hub card instead of a plain emoji.
        badgeText: '24',
        color: '#F97316',
        category: 'Puzzle',
        playerCount: '1–20+',
        duration: '1–5 min',
        description: 'Combine four numbers with +, −, ×, ÷ to reach exactly 24. Play Sprint (solve your own stream of puzzles for points before time runs out) or Race (everyone gets the same problem and the first to solve it wins the point — first to the target score wins).',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'Host picks difficulty (easy / medium / hard / any) and round length',
            'When the round starts, everyone gets the same shuffled queue of puzzles',
            'Tap a number, an operator, then another number to combine them — repeat until one tile is left',
            'When that final tile equals 24, you score and the next puzzle appears',
            'The faster you solve, the more points you earn — stuck puzzles can be Skipped for a small penalty',
            'When the timer hits zero, the highest total score wins'
        ],
        hostPath: '/twentyfour/host',
        playPath: '/twentyfour/play',
        // Solo practice mode — pick a difficulty and solve unlimited puzzles
        // with a running timer and a "Give Up" reveal. Surfaced as a secondary
        // link on the hub card so it doesn't compete with the host CTA.
        practicePath: '/twentyfour/practice?from=hub',
    },
    {
        id: 'herdmind',
        name: 'Herd Mind',
        tagline: 'Match the herd, dodge the Pink Cow',
        emoji: '🐄',
        color: '#8B5E4C',
        category: 'Social',
        playerCount: '3–20+',
        duration: '10–20 min',
        description: 'Everyone answers the same open question on their phone. Score by giving the MOST POPULAR answer — match the herd! Give a one-of-a-kind answer and you\'re stuck with the Pink Cow… and you can\'t win while you\'re holding it.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'Each round a question appears — everyone secretly types an answer before the timer ends',
            'Everyone who gives the most popular answer earns a point — match the herd!',
            'Give a completely unique answer and you\'re landed with the Pink Cow 🐄',
            'You can\'t win while holding the Pink Cow — pass it on by making someone else the odd one out',
            'First to the target score (without the cow) wins the herd!'
        ],
        hostPath: '/herdmind/host',
        playPath: '/herdmind/play',
    },
    {
        id: 'camo',
        name: 'Camo',
        tagline: 'One of you has no idea what the word is',
        emoji: '🦎',
        color: '#5B2A86',
        category: 'Social',
        playerCount: '3–8',
        duration: '10–20 min',
        description: 'Sixteen words sit on the big screen. Everyone\'s phone shows which one is the secret word — everyone except the Chameleon, who has to fake it. One by one you each say a single word out loud to prove you\'re in on it, then the group votes on who was bluffing. Get caught and the Chameleon still has one chance to guess the word and slip away.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name (3–8 players)',
            'Each round shows a topic and a grid of 16 words on the big screen',
            'Your phone secretly reveals the word — hold to peek at it any time',
            'One player is the Chameleon: they see the topic but NOT the word',
            'Taking turns, everyone says ONE word out loud that hints at the secret word',
            'Be too obvious and the Chameleon guesses it; be too vague and you look guilty',
            'The vote opens as soon as the last clue lands — argue it out with the ballot open, then everyone votes on their phone for who they think is faking',
            'If the vote misses (or ties), the Chameleon escapes and scores 2 points',
            'If the Chameleon is caught, they get one guess at the secret word — right, and they still score 1',
            'Catch the Chameleon and beat their guess, and everyone who voted for them scores 1',
            'First player to the target score wins'
        ],
        hostPath: '/camo/host',
        playPath: '/camo/play',
    },
    {
        id: 'catclash',
        name: 'Category Clash',
        tagline: 'One letter, twelve categories, no repeats',
        emoji: '📝',
        color: '#E4572E',
        category: 'Social',
        playerCount: '2–20+',
        duration: '15–25 min',
        description: 'A fast-writing party classic. Every round rolls a random letter, then everyone races the clock to fill in the same twelve categories — every answer has to start with that letter. Points only go to answers nobody else wrote, so think fast AND think differently. Answers are auto-grouped and checked, with the host having the final say.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'The host picks how many rounds and how long each round lasts',
            'Each round a random letter is rolled — it is never repeated later in the game',
            'The same twelve categories appear on every player\'s phone; fill in as many as you can before time runs out',
            'Every answer must start with the round\'s letter ("A", "An" or "The" in front is fine)',
            'When time is up the host reviews each category on the big screen, one at a time',
            'Answers are auto-bucketed and checked — the host can re-bucket anything or drop it in the Invalid pile',
            'You score 1 point per answer that is unique, starts with the letter, and really fits the category',
            'Matching someone else\'s answer scores you both nothing — most points after the final round wins!'
        ],
        hostPath: '/catclash/host',
        playPath: '/catclash/play',
    },
    {
        id: 'noggle',
        name: 'Noggle',
        tagline: 'Find as many words as you can in the letter grid',
        emoji: '🔠',
        color: '#1E5F4F',
        category: 'Puzzle',
        playerCount: '1–20+',
        duration: '3–5 min',
        description: 'Everyone gets the SAME randomly shaken letter grid on their phone. Race the clock to trace as many words as you can — letters must connect in a chain (any of the 8 directions). Longer words score more. Official word-hunt rules and scoring, on boards from 4×4 up to 6×6.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'Host picks the board size (4×4, 5×5, or 6×6) and the time limit',
            'When the round starts, everyone sees the exact same shaken grid',
            'Trace a word by dragging across connected letters — horizontal, vertical, or diagonal neighbours',
            'No reusing the same tile twice in one word; words must be in the dictionary',
            'Longer words score more (3–4=1, 5=2, 6=3, 7=5, 8+=11 points); the "Qu" tile counts as two letters',
            'When the timer hits zero, scores are revealed podium-style — highest total wins!'
        ],
        hostPath: '/noggle/host',
        playPath: '/noggle/play',
        practicePath: '/noggle/practice?from=hub',
    },
    {
        id: 'stackingroyale',
        name: 'Stacking Royale',
        tagline: 'Clear lines. Send trouble. Be the last stack standing.',
        emoji: '🧱',
        color: '#15785E',
        category: 'Puzzle',
        playerCount: '1–30',
        duration: '3–10 min',
        description: 'Play falling blocks on your phone while the shared screen follows the battle. Clear lines and build combos to cancel incoming garbage and send the remainder to a random opponent. Or practice solo with classic endless play, no host required.',
        rules: [
            'Open the host screen, scan its QR code, and enter your name',
            'The host starts when 1–30 players have joined; with one player, play continues until you top out',
            'Move and rotate pieces using buttons, gestures, or a keyboard; fill complete rows to clear them',
            'Use Hold to save a piece, and the ghost and previews to plan your next placement',
            'Bigger clears, combos, T-spins, and back-to-back clears send more garbage',
            'Your attacks cancel queued garbage first, then send any remainder to a random surviving opponent',
            'When your stack tops out you are eliminated; the last survivor wins',
            'Your board keeps playing if you disconnect. Rejoin to restore its current state',
            'Practice solo offers endless play without opponents, with pause and resume'
        ],
        hostPath: '/stackingroyale/host',
        playPath: '/stackingroyale/play',
        practicePath: '/stackingroyale/practice?from=hub',
    },
    {
        id: 'soccerhead',
        name: 'Soccer Head',
        tagline: 'Big-head 2D soccer — your phone is the controller',
        emoji: '⚽',
        color: '#0E3A5F',
        category: 'Arcade',
        playerCount: '1–4 (+CPU)',
        duration: '1–4 min',
        description: 'A fast, physics-y arcade soccer showdown. The match plays out on the shared screen while each player uses their phone as a live controller — move, jump, and kick in real time. Go head-to-head 1v1, or add a CPU opponent to play solo. Highest score when the timer ends wins; a tie triggers sudden-death golden goal.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'It\'s 1v1 — one player on Team Red, one on Team Blue (or add a CPU opponent)',
            'The host sets the match length (1–4 min), then hits Start',
            'Your phone becomes a controller: left/right to move, jump and kick on the right',
            'Double-tap left or right for a quick dash (short cooldown)',
            'Head, body, or boot the ball into the opponent\'s net to score',
            'Highest score when the timer hits zero wins — a tie goes to sudden-death golden goal',
        ],
        hostPath: '/soccerhead/host',
        playPath: '/soccerhead/play',
    },
    {
        id: 'slingsoccer',
        name: 'Sling Soccer',
        tagline: 'Turn-based flick soccer — slingshot your tokens',
        emoji: '🥅',
        color: '#0f5132',
        category: 'Arcade',
        playerCount: '1–6 (+CPU)',
        duration: '3–8 min',
        description: 'A top-down, turn-based soccer showdown played on the shared screen. Each team has five sliding tokens; take turns slingshotting one to knock the ball into the opponent\'s net. Bank shots off the walls, posts and other tokens — the angle of every collision matters. Play up to 3-a-side, or add a CPU to play solo. First team to the goal target wins.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code and join Team Red or Team Blue (up to 3 per team, at least 1 each)',
            'No opponent? The host can add a CPU to play solo',
            'The host sets how many goals win the match (1–10), then hits Kick off',
            'Teams alternate turns; players on a team take turns in join order',
            'On your turn: tap one of your five tokens, then pull back the slingshot on your phone',
            'Pull back further for more power, and angle it to aim — release to flick',
            'Bounce tokens off walls, posts and each other to drive the ball into the net',
            'A token that lands in a goal respawns just outside so it can\'t block shots',
            'After each goal the board resets and the team that conceded kicks off',
            'First team to reach the goal target wins!'
        ],
        hostPath: '/slingsoccer/host',
        playPath: '/slingsoccer/play',
    },
    {
        id: 'rankfive',
        name: 'Rank Five',
        tagline: 'Read the ranker\u2019s mind \u2014 you vs the game',
        emoji: '\uD83E\uDD47',
        color: '#7A5200',
        category: 'Social',
        playerCount: '2\u201320+',
        duration: '10\u201320 min',
        description: 'A co-operative "guess how they think" game. Each round one player secretly ranks 5 random things 1\u20135, then someone else drags the group\u2019s consensus order while everyone discusses \u2014 the ranker has to stay quiet! Every position you nail scores the group a point; every miss scores the game. Everyone ranks once and submits once. Beat the game together to win.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name',
            'Each round, one player is the secret Ranker \u2014 they order 5 random things 1\u20135 however they like',
            'A different player is the Submitter; everyone else can see the 5 things and discuss',
            'The whole group debates the Ranker\u2019s likely order \u2014 but the Ranker must stay silent!',
            'The Submitter drags the group\u2019s consensus order live on the big screen, then locks it in',
            'Each position that matches the Ranker scores the GROUP a point; each miss scores the GAME',
            'Everyone is Ranker once and Submitter once \u2014 beat the game\u2019s score to win together!'
        ],
        hostPath: '/rankfive/host',
        playPath: '/rankfive/play',
    },
    {
        id: 'mazechomp',
        name: 'Maze Chomp',
        tagline: 'Chomp, power up, and eat your rivals',
        emoji: '👻',
        color: '#12123a',
        category: 'Arcade',
        playerCount: '1–4 (+CPU)',
        duration: '5–12 min',
        description: 'A multiplayer Maze Chomp showdown played on the shared screen. Each player steers a chomper from their phone, racing to gobble pellets and cherries for points while dodging four ghosts. Grab a power pellet to turn big and fast — frighten the ghosts and eat smaller players. Die and you\'re out for the round; the highest score among the survivors takes the round. First to the target number of round wins takes the game.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name (2–4 players; add CPU chompers to fill in)',
            'The host sets the round length and how many round wins take the game, then hits Start',
            'Your phone is a D-pad — up/down/left/right steer your chomper on the big screen',
            'Gobble pellets (and the occasional cherry) for points; edges wrap to the opposite side',
            'A ghost eats you if you\'re not powered — die and you\'re out for the rest of the round',
            'Eat a power pellet to turn big and fast for 10 seconds: ghosts flee (eat them for bonus points) and you can eat smaller players',
            'Two chompers of equal size just bounce off each other',
            'When the round ends, the highest score among the players still alive wins the round',
            'First to the target number of round wins takes the whole game!'
        ],
        hostPath: '/mazechomp/host',
        playPath: '/mazechomp/play',
    },
    {
        id: 'bombbrawl',
        name: 'Bomb Brawl',
        tagline: 'Blow up the maze — and everyone in it',
        emoji: '💣',
        color: '#171233',
        category: 'Arcade',
        playerCount: '1–4 (+CPU)',
        duration: '5–12 min',
        description: 'A four-way bomber battle played on the shared screen. Everyone starts in their own corner of a crate-filled arena and drops bombs to blast open paths, grab power-ups and catch their rivals in the blast. Blasts fire in a cross, chain off other bombs, and will happily kill you too. If nobody dies before the clock runs down, sudden death starts and the walls close in. Last bomber standing wins the round — first to the target number of round wins takes the game.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name (2–4 players; add CPU bombers to fill in)',
            'The host drags the roster into spawn order — seat 1 starts top-left, 2 top-right, 3 bottom-left, 4 bottom-right',
            'The host sets the round wins needed, the round length, power-ups on/off and CPU difficulty, then hits Start',
            'Your phone is a thumbstick plus a big Bomb button — move around the arena and drop bombs',
            'Bombs explode in a cross after a short fuse, blasting the first crate in each direction — and any bomber caught in the flames, including you',
            'A bomb caught in another blast detonates instantly, so chain reactions can sweep the whole arena',
            'Blown-up crates reveal power-ups: Extra Bomb, Fire (bigger blast), Speed, and Kick (walk into a bomb to shove it)',
            'If the clock runs low, sudden death begins — indestructible blocks slam down in a spiral and crush anyone left in the open',
            'Last bomber standing wins the round; if everyone dies in the same blast it\'s a draw and the round is replayed',
            'First to the target number of round wins takes the game!'
        ],
        hostPath: '/bombbrawl/host',
        playPath: '/bombbrawl/play',
    },
    {
        id: 'puckball',
        name: 'Puck Ball',
        tagline: 'Two teams, one ball, pure chaos',
        emoji: '🏟️',
        color: '#4E7A3A',
        category: 'Arcade',
        playerCount: '2–8 (+CPU)',
        duration: '3–8 min',
        description: 'Top-down disc soccer on the shared screen. Every player is a circle on the pitch, steered from their phone with a thumbstick and a Kick button. Shove, pass, and blast the ball past the keeper into the opposing net. The pitch grows with the teams — a tight 1v1 rink or a full 4v4 stadium. First team to the score limit wins; if the clock runs out level, it goes to golden goal.',
        rules: [
            'The host opens the game on a shared screen (TV, laptop, etc.)',
            'Players scan the QR code on their phones and enter a name (2–8 players; add CPU players to fill a side)',
            'The host balances the teams — drag players between Red and Blue, or hit Shuffle',
            'The host sets the score limit and the match length, then hits Start',
            'Your phone is a thumbstick plus a big Kick button — steer your disc around the pitch',
            'Bump into the ball to nudge it; tap Kick when you\'re touching it to blast it',
            'Kick it into the opposing net to score — the pitch resets for a kickoff',
            'The pitch size scales with the teams, from a tight 1v1 rink to a full 4v4 stadium',
            'First team to the score limit wins; otherwise the leader when the clock hits zero takes it',
            'Level at full time? Golden goal — next goal wins!'
        ],
        hostPath: '/puckball/host',
        playPath: '/puckball/play',
    },
];

module.exports = games;
